/**
 * one-step-seo — report builders (JSON / Markdown / single-file HTML).
 * HTML is dependency-free with inline CSS.
 */

function esc(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function priorityOrder(a, b) {
  const rank = { P0: 0, P1: 1, P2: 2, P3: 3, pass: 4 };
  return (rank[a.severity] ?? 5) - (rank[b.severity] ?? 5);
}

export function buildReport({ url, finalUrl, scores, findings, parsed, siteFiles, meta }) {
  const sorted = [...findings].sort(priorityOrder);
  const counts = { P0: 0, P1: 0, P2: 0, P3: 0, pass: 0 };
  for (const f of findings) counts[f.severity] = (counts[f.severity] ?? 0) + 1;
  return {
    tool: "one-step-seo",
    version: meta.version,
    url,
    finalUrl,
    checkedAt: new Date().toISOString(),
    scores,
    counts,
    findings: sorted,
    page: {
      title: parsed.title,
      metaDescription: parsed.metaDescription,
      canonical: parsed.canonical,
      wordCount: parsed.wordCount,
      h1: parsed.h1s.map((h) => h.text),
      images: parsed.images.length,
      internalLinks: parsed.internalLinkCount,
      externalLinks: parsed.externalLinkCount,
    },
    site: {
      origin: siteFiles.origin,
      robots: siteFiles.robots.found,
      sitemap: siteFiles.sitemap.found,
      sitemapUrls: siteFiles.sitemap.urlCount,
      llms: siteFiles.llms.found,
    },
  };
}

export function renderMarkdown(report) {
  const L = [];
  L.push(`# one-step-seo report`);
  L.push(``);
  L.push(`- URL: ${report.url}`);
  L.push(`- Final URL: ${report.finalUrl}`);
  L.push(`- Checked: ${report.checkedAt}`);
  L.push(`- Search SEO: **${report.scores.search.score}/100 (${report.scores.search.band})**`);
  L.push(`- AI Visibility: **${report.scores.ai.score}/100 (${report.scores.ai.band})**`);
  L.push(`- Counts: P0=${report.counts.P0} P1=${report.counts.P1} P2=${report.counts.P2} P3=${report.counts.P3} pass=${report.counts.pass}`);
  L.push(``);
  L.push(`## Priority actions`);
  const actionable = report.findings.filter((f) => f.severity !== "pass");
  if (actionable.length === 0) L.push(`No issues found. Nice.`);
  for (const f of actionable) {
    L.push(`### [${f.severity}] ${f.title} (${f.id})`);
    L.push(`- Category: ${f.category}`);
    L.push(`- Evidence: ${f.evidence}`);
    if (f.fix) L.push(`- Fix: ${f.fix}`);
  }
  L.push(``);
  L.push(`## Passed checks`);
  for (const f of report.findings.filter((f) => f.severity === "pass")) {
    L.push(`- ${f.title} (${f.id})`);
  }
  L.push(``);
  L.push(`---`);
  L.push(`Generated by one-step-seo v${report.version}. Two scores, never blended.`);
  return L.join("\n") + "\n";
}

export function renderHtml(report) {
  const rows = report.findings
    .map(
      (f) =>
        `<tr class="sev-${esc(f.severity)}"><td><strong>${esc(f.severity)}</strong></td><td>${esc(f.title)}<br><small>${esc(f.id)} · ${esc(f.category)}</small></td><td>${esc(f.evidence).slice(0, 300)}</td><td>${esc(f.fix || "—").slice(0, 300)}</td></tr>`
    )
    .join("\n");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>one-step-seo report — ${esc(report.finalUrl)}</title>
<style>
:root{color-scheme:light dark}
body{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;margin:0;padding:32px;line-height:1.55;max-width:1080px;margin-inline:auto}
.cards{display:flex;gap:16px;flex-wrap:wrap;margin:16px 0 24px}
.card{border:1px solid #ccc;border-radius:12px;padding:16px 20px;min-width:220px}
.score{font-size:40px;font-weight:800}
table{border-collapse:collapse;width:100%;font-size:14px}
th,td{border:1px solid #ccc;padding:8px 10px;text-align:left;vertical-align:top}
tr.sev-P0{background:rgba(220,38,38,.08)}
tr.sev-P1{background:rgba(234,88,12,.08)}
.meta{color:#555;font-size:13px}
code{background:rgba(127,127,127,.15);padding:1px 6px;border-radius:6px}
</style>
</head>
<body>
<h1>one-step-seo report</h1>
<p class="meta">URL: <code>${esc(report.url)}</code><br>Final: <code>${esc(report.finalUrl)}</code><br>Checked: ${esc(report.checkedAt)} · v${esc(report.version)}</p>
<div class="cards">
<div class="card"><div>Search SEO</div><div class="score">${report.scores.search.score}<small>/100 ${esc(report.scores.search.band)}</small></div></div>
<div class="card"><div>AI Visibility</div><div class="score">${report.scores.ai.score}<small>/100 ${esc(report.scores.ai.band)}</small></div></div>
<div class="card"><div>Counts</div><div>P0=${report.counts.P0} · P1=${report.counts.P1} · P2=${report.counts.P2} · P3=${report.counts.P3} · pass=${report.counts.pass}</div></div>
</div>
<table>
<thead><tr><th>Priority</th><th>Check</th><th>Evidence</th><th>Fix</th></tr></thead>
<tbody>
${rows}
</tbody>
</table>
<p class="meta">Generated by one-step-seo. Two scores, never blended.</p>
</body>
</html>
`;
}
